name: Deploy via FTP
on: push
jobs:
  deploy:
    name: Deploy FFM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload Update Page
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: updating/
          remoteDir: /
          options: --verbose --ascii --no-perms

      - name: Upload Assets
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: dist/
          remoteDir: /
          options: --verbose --delete --parallel --ascii --exclude=index.html --no-perms

      - name: Wait for 30 seconds
        run: sleep 30

      - name: Upload Actual Index
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: dist/
          remoteDir: /
          options: --verbose --ascii --overwrite --include=index.html --no-perms